razer functions

diff --git a/resources/bashrc b/resources/bashrc
--- a/resources/bashrc
+++ b/resources/bashrc
@@ -14,29 +14,61 @@ alias update-system="sudo apt -qqy update && sudo apt -qqy dist-upgrade"
 alias shutdown-system="sudo shutdown -h now"
 alias leavemealone="touch $HOME/.leavemealone"
 
+
+
 if [ ! -f $HOME/.leavemealone ];then
-  echo ""
-  echo "quake:"
-  echo "run quake (using ezquake, qw compatible): quake"
-  echo "change quake (ezquake) assets preset: quakepreset"
-  echo "update quake (ezquake) from git: update-quake"
-  if [ ! -z "$DISPLAY" ];then
-    echo "run afterquake (using fte, qw and netquake compatible): quake-afterquake"
-  fi
-  echo ""
-  echo "other:"
-  if [ ! -z "$DISPLAY" ];then
-  	echo "run a web browser: browser"
-  	echo "configure display(s): lxrandr"
-  	echo "configure networking: connman-gtk (systray icon)"
-  	echo "disable nvidia driver (use opensource driver nouveau): nvidia-disable"
-  	echo "enable nvidia driver: nvidia-enable"
-  else
-    echo "configure networking: connmanctl"
-  fi
-  echo "update system: update-system"
-  echo "shutdown system: shutdown-system"
-  echo ""
-  echo "to disable these messages: leavemealone"
-  echo ""
+	echo ""
+	echo "quake:"
+	echo "run quake (using ezquake, qw compatible): quake"
+	echo "change quake (ezquake) assets preset: quakepreset"
+	echo "update quake (ezquake) from git: update-quake"
+	if [ ! -z "$DISPLAY" ];then
+		echo "run afterquake (using fte, qw and netquake compatible): quake-afterquake"
+	fi
+	echo ""
+
+	#razer mouse functions
+	if ls /sys/module/razermouse/drivers/hid:razermouse/*/device_mode > /dev/null;then
+		function razer-dpi(){
+			if [ ! -z "$1" ];then
+				hex=$(printf "%04x" "$1")
+				echo -en "\x${hex:0:2}\x${hex:2:4}"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/dpi >/dev/null
+				if [ $? -ne 0 ];then
+					echo "setting dpi failed."
+				else
+					echo "dpi set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/dpi)."
+				fi
+			fi
+		}
+		function razer-rate(){
+			if [ ! -z "$1" ];then
+				echo -en "$1"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate >/dev/null
+				if [ $? -ne 0 ];then
+					echo "setting polling rate failed."
+				else
+					echo "polling rate set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate)."
+				fi
+			fi
+		}
+		echo "razer mouse:"
+		echo "set dpi: razer-dpi XXX"
+		echo "set polling rate: razer-poll XXX"
+		echo ""
+	fi
+
+	echo "other:"
+	if [ ! -z "$DISPLAY" ];then
+		echo "run a web browser: browser"
+		echo "configure display(s): lxrandr"
+		echo "configure networking: connman-gtk (systray icon)"
+		echo "disable nvidia driver (use opensource driver nouveau): nvidia-disable"
+		echo "enable nvidia driver: nvidia-enable"
+	else
+		echo "configure networking: connmanctl"
+	fi
+	echo "update system: update-system"
+	echo "shutdown system: shutdown-system"
+	echo ""
+	echo "to disable these messages: leavemealone"
+	echo ""
 fi
