move user messages into profile

diff --git a/resources/bashrc b/resources/bashrc
--- a/resources/bashrc
+++ b/resources/bashrc
@@ -1,3 +1,39 @@
+#razer mouse functions
+if ls /sys/module/razermouse/drivers/hid:razermouse/*/device_mode > /dev/null 2>&1;then
+  function razer-dpi(){
+    if [ ! -z "$1" ];then
+      hex=$(printf "%04x" "$1")
+      echo -en "\x${hex:0:2}\x${hex:2:4}"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/dpi >/dev/null 2>&1
+      if [ $? -ne 0 ];then
+        echo "setting dpi failed."
+      else
+        echo "dpi set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/dpi)."
+        echo "$1" > ${HOME}/.razer_dpi
+      fi
+    fi
+  }
+  function razer-rate(){
+    if [ ! -z "$1" ];then
+      echo -en "$1"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate >/dev/null
+      if [ $? -ne 0 ];then
+        echo "setting polling rate failed."
+      else
+        echo "polling rate set to $(cat /sys/module/razermouse/drivers/hid:razermouse/*/poll_rate)."
+        echo "$1" > ${HOME}/.razer_rate
+      fi
+    fi
+  }
+  function razer-mode(){
+    if [ "$1" = "1" ];then
+      echo -n -e "\x03\x00"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/device_mode >/dev/null
+    else
+      echo -n -e "\x00\x00"|sudo tee /sys/module/razermouse/drivers/hid:razermouse/*/device_mode >/dev/null
+      echo "$1" > ${HOME}/.razer_mode
+    fi
+  }
+fi
+
+#custom aliases
 alias quake="currentdir=$(pwd);cd $HOME/quake;./quake;cd \"$currentdir\""
 alias quake-afterquake="currentdir=$(pwd);cd $HOME/quake-afterquake;nice -n -5 ./fteqw64;cd \"$currentdir\""
 alias quakepreset="currentdir=$(pwd);cd $HOME/quake;./choose-qw.sh;cd \"$currentdir\""
@@ -9,38 +45,3 @@ alias nvidia-enable="export DEBIAN_FRONTEND=noninteractive;sudo apt -qqy update;
 alias update-system="sudo apt -qqy update && sudo apt -qqy dist-upgrade"
 alias shutdown-system="sudo shutdown -h now"
 alias leavemealone="touch $HOME/.leavemealone"
-
-if [ ! -f $HOME/.leavemealone ];then
-	echo ""
-	echo "quake :"
-	echo "run quake (using ezquake, qw compatible): quake"
-	echo "change quake (ezquake) assets preset: quakepreset"
-	echo "update quake (ezquake) from git: update-quake"
-	if [ ! -z "$DISPLAY" ];then
-		echo "run afterquake (using fte, qw and netquake compatible): quake-afterquake"
-	fi
-	echo ""
-	#razer mouse functions
-	if ls /sys/module/razermouse/drivers/hid:razermouse/*/device_mode > /dev/null 2>&1;then
-		echo "razer mouse :"
-		echo "set dpi: razer-dpi XXX"
-		echo "set polling rate: razer-poll XXX"
-		echo ""
-	fi
-	echo "other :"
-	if [ ! -z "$DISPLAY" ];then
-		echo "run a web browser: browser"
-		echo "run a file browser: filebrowser"
-		echo "configure display(s): lxrandr"
-		echo "configure networking: connman-gtk (systray icon)"
-		echo "disable nvidia driver (use opensource driver nouveau): nvidia-disable"
-		echo "enable nvidia driver: nvidia-enable"
-	else
-		echo "configure networking: connmanctl"
-	fi
-	echo "update system: update-system"
-	echo "shutdown system: shutdown-system"
-	echo ""
-	echo "to disable these messages: leavemealone"
-	echo ""
-fi
